################################################################################
# Encryption Vars
################################################################################

variable "crypto_key" {
  type        = string
  description = "Specify the Name of the Crypto Key used to encrypt the Cloud Run resource."
}

################################################################################
# VPC Serverless Access Connector Vars
################################################################################

variable "vpc_access_connector" {
  type        = string
  description = "(Required) The name of the VPC Serverless Access Connector to attach to for access to resources within the Private VPC ranges."
}

variable "vpc_access_egress" {
  type        = string
  description = "(Optional) Egress access via VPC. Currently all traffic is routed through the VPC connector (all-traffic). Defaults to all-traffic."
  default     = "all-traffic"

  validation {
    condition = anytrue([
      var.vpc_access_egress == "all-traffic"
    ])
    error_message = "The currently allowed options for routing egress traffic through the VPC connector are: all-traffic."
  }
}

################################################################################
# Cloud Run Vars
################################################################################

variable "name" {
  type        = string
  default     = ""
  description = "(Required) Name must be unique within a namespace, within a Cloud Run region. The name is primarily intended for creation idempotence and configuration definition. Cannot be updated."
}

variable "location" {
  type        = string
  default     = ""
  description = "(Required) The location of the cloud run instance. eg us-central1"
}

variable "project_id" {
  type        = string
  description = "(Optional) The ID of the project in which the resource belongs. If it is not provided, the project ID listed in the provider is used."
  default     = ""
}

variable "autogenerate_revision_name" {
  type        = bool
  default     = false
  description = "(Optional) If set to true, the revision name (template.metadata.name) will be omitted and autogenerated by Cloud Run. This cannot be set to true while template.metadata.name is also set. (For legacy support, if template.metadata.name is unset in state while this field is set to false, the revision name will still autogenerate.)"
}

variable "image" {
  type        = string
  description = "(Required) Docker image name. This is most often a reference to a container located in the Artifact Registry."
  # Removing Validation: Unable to use custom, private registries: https://cloud.google.com/run/docs/deploying#images
  # validation {
  #   error_message = "Image must be one of: [\"https://quay.apps.lz-prod.ent-ocp4-useast1.aws.internal.das/\", \"https://quay.apps.lz-np2.ent-ocp4-useast1.aws.internal.das/\"]."
  #   condition     = contains(["https://quay.apps.lz-np2.ent-ocp4-useast1.aws.internal.das/", "https://quay.apps.lz-prod.ent-ocp4-useast1.aws.internal.das/"], var.image)
  # }
}

variable "args" {
  type        = any
  default     = []
  description = "Arguments to the entrypoint. The docker image's CMD is used if this is not provided."
}

variable "command" {
  type        = any
  default     = []
  description = "Entrypoint array. Not executed within a shell. The docker image's ENTRYPOINT is used if this is not provided."
}

variable "env_vars" {
  type = list(object({
    value = string
    name  = string
  }))
  default     = []
  description = " (Optional) List of environment variables to set in the container."
}

variable "ports" {
  type = list(object({
    name           = string
    container_port = number
  }))
  default     = []
  description = "Port which the container listens to. The name can only be either http1 or h2c. The protocol can only be TCP."
}

variable "volumes" {
  type = list(object({
    name = string
    secret = set(object({
      secret_name = string
      items       = map(string)
    }))
  }))
  description = "(Optional) Volume represents a named volume to be mounted in a container (especially when using secrets)."
  default     = []
}

variable "volume_mounts" {
  type = list(object({
    mount_path = string
    name       = string
  }))
  description = "Volume Mounts to be attached to the container (especially when using secrets)"
  default     = []
}

variable "startup_probe" {
  type        = any
  description = "(Optional) Startup probe of application within the container. All other probes are disabled if a startup probe is provided, until it succeeds. Container will not be added to service endpoints if the probe fails."
  default     = null
}

variable "liveness_probe" {
  type        = any
  description = "(Optional) Periodic probe of container liveness. Container will be restarted if the probe fails."
  default     = null
}

variable "limits" {
  type        = map(string)
  description = "Resource limits to provide to the container."
  default     = {}
}

variable "requests" {
  type        = map(string)
  description = "Resource requests to provide to the container."
  default     = {}
}

variable "container_concurrency" {
  type        = number
  default     = 0
  description = "(Optional) Container Concurrency specifies the maximum allowed in-flight (concurrent) requests per container of the Revisions, specified as a number: 0, 1, 2-N. 0: Thread-safe, the system should manage the max concurrency. This is the default value. 1: Not thread-safe. Single concurrency, 2-N: thread-safe, max concurrency of N."
}

variable "timeout_seconds" {
  type        = number
  default     = 300
  description = "(Optional) TimeoutSeconds holds the max duration the instance is allowed for responding to a request."
}

variable "service_account_name" {
  type        = string
  description = " (Optional) Email address of the IAM service account associated with the revision of the service. The service account represents the identity of the running revision, and determines what permissions the revision has."
  default     = null
}

variable "template_labels" {
  type        = map(string)
  description = "Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and routes. "
  default     = { type = "test" }
}

variable "additional_template_annotations" {
  type        = map(string)
  description = "Any addtional template annotations to the specification provided by the end-users."
  default     = {}
}

variable "labels" {
  type        = map(string)
  description = "(Required) Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and routes."
}

variable "additional_service_annotations" {
  type        = map(string)
  description = "Any addtional annotations to the service provided by the end-users."
  default     = {}
}

variable "traffic" {
  type        = any
  description = "(Optional) Traffic specifies how to distribute traffic over a collection of Knative Revisions and Configurations Structure"
  default = [{
    latest_revision = true
    percent         = 100
    revision_name   = "v0.0.1"
    tag             = null
  }]
}

###########################################################
# Cloud Run Built-in Annotations via Template and Service
###########################################################

## Service Annotations

variable "ingress" {
  type        = string
  description = "Ingress settings for the service. Allowed values: \"internal\" only."
  default     = "internal"

  validation {
    condition = anytrue([
      var.ingress == "internal"
    ])
    error_message = "The currently allowed options for Ingress are: internal."
  }
}

variable "run_description" {
  type        = string
  description = "The description of the Run Service"
  default     = ""
}

## Template Annotations

variable "minscale" {
  type        = number
  description = "Sets the minimum number of container instances of the Revision to run."
  default     = null
}

variable "maxscale" {
  type        = number
  description = "sets the maximum number of container instances of the Revision to run."
  default     = null
}

variable "cloudsql_instances" {
  type        = string
  description = "sets the Cloud SQL instances the Revision connects to."
  default     = ""
}

variable "execution_environment" {
  type        = string
  description = "sets the execution environment where the application will run."
  default     = ""
}

variable "post_key_revocation_action_type" {
  type        = string
  description = "sets the action type after CMEK key revocation."
  default     = ""
}

###################################
# Cloud Run Timeouts
###################################

variable "create_timeout" {
  type        = number
  description = "Creation Timeout of Cloud Run Resource."
  default     = 20
}

variable "delete_timeout" {
  type        = number
  description = "Delete Timeout of Cloud Run Resource."
  default     = 20
}

variable "update_timeout" {
  type        = number
  description = "Update Timeout of Cloud Run Resource."
  default     = 20
}
